# Generated by Django 4.1.1 on 2022-09-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhp', '0002_study_interview_history_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
