# Generated by Django 4.1.1 on 2022-09-06 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jhp', '0005_alter_application_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='jhp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='start_date',
            field=models.DateField(),
        ),
    ]
