# Generated by Django 4.1.1 on 2022-09-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jhp', '0006_alter_history_user_alter_user_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='strat_date',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='study',
            name='date',
            field=models.DateField(),
        ),
    ]
